# Generated by Django 4.0.5 on 2022-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signs',
            name='activity_details',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='signs_details',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
