# Generated by Django 4.0.5 on 2022-07-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_signs_activity_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
