# Generated by Django 4.0.3 on 2022-07-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('Glasses', 'Glasses'), ('Product', 'Product')], max_length=200, null=True),
        ),
    ]
