# Generated by Django 4.0.3 on 2022-07-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], default='Unpaid', max_length=200, null=True),
        ),
    ]
